### ISSUE TITLE
Please add a (small) documentation, as a README.md file

### ISSUE THREAD

**Issue by Naereen** [nbnbhattarai/recommender#2]
Hi again!
Without any explanation, nobody can know what this project does, how to install it or use it.
Please try to add a (small) documentation! Using a README.md markdown file is helpful as it will be displayed by default when someone sees [the project page](https://github.com/nbnbhattarai/recommender/).
Thanks!

**Comment by abpaudel** [comment]
I have added a brief README. Hope it will be useful. I will add a more detail someday when I'm free.

**Comment by Naereen** [comment]
[![LGTM](http://www.lgtm.in/p/ClbKhlEVp)](http://www.lgtm.in/i/ClbKhlEVp)
LGTM
